---

- name: Create user
  user:
    name: devpi
    state: present

- name: Install python3-pip
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-pip
  when: ansible_python_version.startswith('3')

- name: Install python-pip
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip
  when: ansible_python_version.startswith('2')

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest

- name: Install devpi
  become: yes
  become_user: devpi
  pip:
    name: devpi-server
    state: latest
    virtualenv: /home/devpi/.env
  notify: restart devpi

- name: Devpi init
  become: yes
  become_user: devpi
  command: /home/devpi/.env/bin/devpi-server --init
  register: devpi_init
  args:
    chdir: /home/devpi
    creates: /home/devpi/.devpi

- name: Create systemd directory
  file:
    path: /etc/systemd/system
    state: directory

- name: Systemd service
  template:
    src: etc/systemd/system/devpi-server.service.j2
    dest: /etc/systemd/system/devpi-server.service
  notify: restart devpi

- name: Start & enable service
  systemd:
    name: devpi-server.service
    state: started
    enabled: yes
